import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const lato = Lato({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
    <Head>
    <link rel="icon" href="/favicon.ico" sizes="any" />
    </Head>
      <body className={lato.className}>{children}</body>
    </html>
  )
}
